### PR TITLE
Add nil properties to outbound JSON

### PR DESCRIPTION
**Pull request by nunobaldaia**
Include `nil` properties on the outbound JSON. Otherwise updating some value to `nil` won't be noticed, at least for some APIs.

### CODE REVIEW

**Comment by matthewcheok** [comment]
Sorry I was going to wait for nit to be fixed. Did I miss that?

**Comment by nunobaldaia** [comment]
Ok, sorry! I've fixed the indentation.

**Comment by matthewcheok** [comment]
Thanks!

**Comment by nunobaldaia** [comment]
Thank you!

**Pull request merged**
