### PR TITLE
Added deepCopy

### PR DESCRIPTION
**Pull request by raspu**
deepCopy will create a shallow copy of an object, and will recursively create shallow copies of any other referenced object.

### CODE REVIEW

**Comment by matthewcheok** [comment]
Not to nitpick but shouldn't the method be just called `deepCopy`?

**Comment by raspu** [comment]
Hahaha you are right, sorry. My english failed me, I mixed hollow with shallow, things that happens when you aren't a native speaker. :). I will rename it

**Comment by matthewcheok** [comment]
Thanks again!

**Comment by raspu** [comment]
Thank you, this library make Realm much more useful!

**Pull request merged**
